version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: ds_todo__db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ds_todo_backend:v1
    container_name: todo_backend
    depends_on:
      - db
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      PORT: 9000
    ports:
      - 9000:9000
volumes:
  pgdata:
