version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - todoLab

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: loasit00/backend:v1
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      PORT: 8080
    ports:
      - 8080:8080
    networks:
      - todoLab

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: loasit00/frontend:v1
    container_name: frontend
    environment:
      - SERVER_PORT=8090
      - BACKEND_ENDPOINT=http://backend:8080/todo
    ports:
      - "8090:8090"
    depends_on:
      - backend
    networks:
      - todoLab
volumes:
  pgdata:

networks:
  todoLab:
    name: todoLab
