version: '3'
services:
  ds_todo_db:
    image: postgres:alpine
    restart: always
    container_name: ds_todo_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - todoLab

  ds_todo_backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: loasit00/ds_todo_backend:v1
    container_name: ds_todo_backend
    depends_on:
      - ds_todo_db
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgres://postgres:postgres@ds_todo_db:5432/postgres
      PORT: 8080
    ports:
      - 8080:8080
    networks:
      - todoLab

  ds_todo_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: loasit00/ds_todo_frontend:v1
    container_name: ds_todo_frontend
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
      - BACKEND_ENDPOINT=https://8080-loasit00-paralleleverte-664y5bfzfq2.ws-eu100.gitpod.io/todo
    depends_on:
      - ds_todo_backend
    networks:
      - todoLab
volumes:
  pgdata:

networks:
  todoLab:
    name: todoLab
